name: Automatización 🤖

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master
    paths-ignore:
      - "**/*.md"
  pull_request_target:
  issues:
    types: 
      - opened
      - reopened
      - transferred

jobs:
  project:
    name: Actualizar el proyecto 📊
    runs-on: ubuntu-latest
    steps:
      - name: Añadir al proyecto
        uses: actions/add-to-project@v0.5.0
        if: ${{ github.event_name == 'pull_request_target' || github.event_name == 'issues' }}
        continue-on-error: true
        with:
          project-url: https://github.com/orgs/us-ferferga/projects/2
          github-token: ${{ secrets.DECIDE_PROJECT_SECRET }}

  label:
    name: Etiquetado 🏷️
    runs-on: ubuntu-latest
    steps:
      - name: Etiquetar PR dependiendo de los archivos modificados
        uses: actions/labeler@v4
        if: ${{ github.event_name == 'pull_request_target' }}
        continue-on-error: true

      - name: Comprobar todos los PR para conflictos ⛔
        uses: eps1lon/actions-label-merge-conflict@v2.1.0
        if: ${{ github.event_name == 'pull_request_target' }}
        with:
          dirtyLabel: "conflictos"
          repoToken: ${{ github.token }}
