name: Automation 🤖

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  push:
    branches:
      - master
    paths-ignore:
      - "**/*.md"
  pull_request_target:
  issues:

jobs:
  project:
    name: Actualizar el proyecto 📊
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.3
        if: ${{ github.event_name == 'pull_request_target' || github.event_name == 'issues' }}
        continue-on-error: true
        with:
          project: Decide
          column: En progreso
          repo-token: ${{ secrets.DECIDE_SECRET }}

  label:
    name: Labeling 🏷️
    runs-on: ubuntu-latest
    steps:
      - name: Label PR depending on modified files
        uses: actions/labeler@v4
        if: ${{ github.event_name == 'pull_request_target' }}
        continue-on-error: true
        with:
          repo-token: "${{ secrets.DECIDE_SECRET }}"

      - name: Check all PRs for merge conflicts ⛔
        uses: eps1lon/actions-label-merge-conflict@v2.1.0
        with:
          dirtyLabel: "conflictos"
          repoToken: ${{ secrets.DECIDE_SECRET }}
